version: '2'
# DEPRECATED
services:
  mariadb:
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=famfun_dev
      - MARIADB_DATABASE=familyfund_dev
      - MARIADB_PASSWORD=1234
      - MARIADB_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - ./datadir_dev:/var/lib/mysql

  familyfund:
    environment:
      - DB_DATABASE=familyfund_dev
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - APP_ENV=local
    ports:
      - 3000:8000
