<?php

namespace Tests\Feature;

use App\Models\Asset;
use App\Models\AssetPrice;
use App\Models\PortfolioExt;
use App\Models\PositionUpdate;
use App\Models\SymbolPosition;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Nette\Utils\DateTime;
use Tests\TestCase;
use Tests\ApiTestTrait;
use const null;

class PositionUpdateApiExtTest extends TestCase
{
    use ApiTestTrait, WithoutMiddleware, DatabaseTransactions, BulkStoreTest;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setupBulkTest('position',
            '/api/portfolio_assets_bulk_update',
            SymbolPosition::factory(),
            PositionUpdate::factory()
        );
    }

    public function getChildren($asset) {
        $portfolio = PortfolioExt::where('source', $this->post['source'])->get()->first();
        $query = $portfolio->positionHistory($asset->id);
        return $query;
    }

    public function testMissingOptionalFields()
    {
//        $this->_testUnsetSymbol('type', 200);
    }

    public function testCash()
    {
        $arr = $this->createSampleReq();
        $arr['symbols'][] = $this->makeSymbol('CASH');
        $this->postAPI($arr);

        $arr = $this->createSampleReq();
        $arr['symbols'][] = $this->makeSymbol(null, 'CSH');
        $this->postAPI($arr);
    }
}
