<?php

namespace Tests\Feature;

use App\Models\PriceUpdate;
use App\Models\SymbolPrice;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\DataFactory;
use Tests\TestCase;
use Tests\ApiTestTrait;
use const null;

class PriceUpdateApiExtTest extends TestCase
{
    use ApiTestTrait, WithoutMiddleware, DatabaseTransactions, BulkStoreTest;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setupBulkTest('price',
            '/api/asset_prices_bulk_update',
            SymbolPrice::factory(),
            PriceUpdate::factory(),
            '2000-01-01',
            1.0
        );
    }

    public function getChildren($asset) {
        return $asset->assetPrices()->get();
    }

    public function testMissingOptionalFields()
    {
//        $this->_testUnsetSymbol('type', 200);
    }

    public function testCashErrors()
    {
        $assetsArr = $this->createSampleReq();
        $assetsArr['symbols'][] = $this->makeSymbol('CASH');
        $this->postError($assetsArr);

        $assetsArr = $this->createSampleReq();
        $assetsArr['symbols'][] = $this->makeSymbol(null, 'CSH');
        $this->postError($assetsArr);
    }

}
